[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "memory-journal-mcp"
version = "2.0.0"
description = "Project context management for AI-assisted development - Persistent knowledge graphs and intelligent context recall across fragmented AI threads"
authors = [
    {name = "Chris LeRoux", email = "writenotenow@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10.12"
dependencies = [
    "mcp>=1.0.0",
]
keywords = ["mcp", "context-management", "project-management", "ai-assistant", "knowledge-graph", "developer-tools", "git", "github-projects", "model-context-protocol", "persistent-memory", "thread-continuity"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11", 
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing",
    "Topic :: Security",
]

[project.urls]
Homepage = "https://github.com/neverinfamous/memory-journal-mcp"
Repository = "https://github.com/neverinfamous/memory-journal-mcp"
Issues = "https://github.com/neverinfamous/memory-journal-mcp/issues"
Documentation = "https://github.com/neverinfamous/memory-journal-mcp/wiki"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "mypy>=1.0",
]

[project.scripts]
memory-journal-mcp = "server:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.wheel.sources]
"src" = "memory_journal_mcp"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
strict = true
