name = "memory-journal-mcp-remote"
compatibility_date = "2025-09-15"
main = "src/remote-server.js"
compatibility_flags = ["nodejs_compat"]

# D1 database for full persistence
[[d1_databases]]
binding = "DB"
database_name = "memory-journal-full"
database_id = "4058385b-0c08-4419-a8da-775e5cf9d43c"

# KV for caching and embeddings
[[kv_namespaces]]
binding = "CACHE"
id = "d6199ec925604908807f196b6bef5a8c"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"