name = "memory-journal-mcp-remote"
compatibility_date = "2025-09-15"
main = "src/remote-server.js"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"