/**
 * Server instructions for Memory Journal MCP.
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions/*.md instead,
 *     then run: npm run generate:instructions
 *
 * Slim instructions are sent to MCP clients during initialization.
 * Detailed help is available on-demand via memory://help resources.
 * Instructions are dynamically generated based on enabled tool groups
 * and instruction level for token efficiency.
 */

import type { ToolGroup } from '../types/index.js'
import { TOOL_GROUPS, getEnabledGroups } from '../filtering/tool-filter.js'

/**
 * Resource definition for instruction generation
 */
export interface ResourceDefinition {
    uri: string
    name: string
    description?: string
}

/**
 * Prompt definition for instruction generation
 */
export interface PromptDefinition {
    name: string
    description?: string
}

/**
 * Latest entry snapshot for initial briefing
 */
export interface LatestEntrySnapshot {
    id: number
    timestamp: string
    entryType: string
    content: string
}

/**
 * Instruction detail level for token efficiency
 * - essential: ~300 tokens - Core behaviors + quick access (for token-constrained clients)
 * - standard: ~350 tokens - + help pointers for enabled groups
 * - full: ~500 tokens - + active tools/prompts summary
 */
export type InstructionLevel = 'essential' | 'standard' | 'full'

// =============================================================================
// Composable Instruction Segments
// =============================================================================

/**
 * Core instructions — always included regardless of enabled groups.
 * Contains quick access, help pointers, and essential behavioral guidance.
 */
const CORE_INSTRUCTIONS = `# memory-journal-mcp

## Quick Access

| Purpose         | Action                      |
| --------------- | --------------------------- |
| Session context | \`memory://briefing\`         |
| Recent entries  | \`memory://recent\`           |
| Health/time     | \`memory://health\`           |
| Full context    | \`get-context-bundle\` prompt |

## Help Resources

Read \`memory://help\` for tool group index and available help resources.
Read \`memory://help/{group}\` for per-group tool reference (parameters, annotations, examples).
Only help resources for your enabled tool groups are registered.

## Behaviors

### Essential Session Start

1. You **MUST** read the \`memory://briefing/{repo_name}\` at the start of each chat!
2. Use the standard MCP \`read_resource\` tool for this (do NOT use Code Mode/execute_code).
3. Infer the \`repo_name\` from the user's prompt or your active workspace context.
4. **ACKNOWLEDGE FLAGS**: If the briefing JSON contains \`activeFlags\` (count > 0), you MUST print an alert ABOVE the table: \`⚠️ **{count} active flag(s)** — review before proceeding.\` followed by each flag (\`🚩 {flag_type} → @{target_user}: {preview}\`).
5. **RENDER TABLE**: Parse the remaining JSON into a dense 2-column Markdown Table (Field, Value).
   - **RESTRICTION**: NO bulleted lists inside the table. Do NOT truncate summaries or issues.
   - **FORMATTING**: Group related properties (use \`<br>\` for line breaks).
   - **REQUIRED GROUPS**: GitHub, Issues, Entry Counts, Latest Entries/Summaries, Analytics, Milestones, Workspaces.
6. **STOP & WAIT**: Do NOT autonomously resume past tasks or start work on new issues. The briefing is strictly for context.

- **AntiGravity**: Tools are \`mcp_{name}_{tool}\` → server name = \`memory-journal-mcp\`
- **Cursor**: Tools are \`user-{name}-{tool}\` → server name = \`user-memory-journal-mcp\`
- **Other clients**: Use configured name exactly. Use tool-prefix discovery if unsure.

### Journal Behaviors

- **Personal vs Team**: **ALWAYS use the personal journal** (e.g., \`create_entry\`) by default. ONLY save to the team journal (e.g., \`team_create_entry\`) if the user explicitly requests it.
- **Create entries for**: implementations, decisions, bug fixes, milestones, user requests to "remember"
- **Search before**: major decisions, referencing prior work, understanding project context. Use \`sort_by: "importance"\` on \`search_entries\`, \`get_recent_entries\`, or \`search_by_date_range\` to surface structurally significant entries (decisions, milestones, highly-connected nodes) over simply recent ones.
- **Analyze insights**: Use cross-project insights (\`get_cross_project_insights\`) before defining architectures. Use \`team_get_collaboration_matrix\` to evaluate team health, cross-author activity patterns, and collaboration impact. Use repo insights (\`memory://github/insights\`) to gauge traction. View \`memory://insights/digest\` and \`memory://insights/team-collaboration\` for automated analytics snapshots.

### Session Summaries

Use \`create_entry\` to record session summaries. Required fields:

- \`entry_type: "retrospective"\`
- \`tags: ["session-summary"]\` (plus relevant domain/activity tags)
- \`project_number\` from the briefing

Structure content with these sections:

- \`## Accomplished\` — What was done this session
- \`## Unfinished / Blocked\` — What remains or what's blocked
- \`## Context for Next Session\` — Key context the next agent needs

Do NOT create session summaries for testing passes where everything passed and no code changes were made. Only summarize sessions with substantive work.

### Entry Type Selection

Choose the correct \`entry_type\` — do NOT default everything to \`personal_reflection\`:

- \`retrospective\` — Session summaries, certification reports, any "what was accomplished" recap
- \`bug_fix\` — Specific bug identification and/or resolution
- \`project_decision\` — Architecture decisions, pattern adoptions, technology choices
- \`planning\` — Roadmaps, sprint plans, project initialization
- \`code_review\` — Security audits, code quality reviews, copilot findings
- \`technical_note\` — Implementation notes, gotchas, reference documentation
- \`feature_implementation\` — New feature completions
- \`research\` — Investigation, benchmarking, evaluation of alternatives
- \`meeting_notes\` — Meeting minutes, sync notes, discussion summaries
- \`learning\` — Lessons learned, tutorials completed, skill acquisition
- \`standup\` — Daily standup notes, status updates
- \`milestone\` — Major project milestones, release checkpoints
- \`technical_achievement\` — Significant technical accomplishments
- \`enhancement\` — Incremental improvements, optimizations
- \`development_note\` — Day-to-day development context and progress
- \`adversarial_review\` — Adversarial audit findings, red-team results
- \`plan_draft\` — Draft plans awaiting review or refinement
- \`plan_refinement\` — Iterated plan revisions based on feedback
- \`copilot_validation\` — Copilot review validation results
- \`system_integration_test\` — Integration test runs and results
- \`test_entry\` — Test data or test-related entries
- \`flag\` — Auto-assigned by Hush Protocol tools (\`team_pass_flag\`). Do NOT set manually.
- \`other\` — Anything that doesn't fit the above categories
- \`personal_reflection\` — Only for genuinely personal notes that don't fit above

### Tag Taxonomy

Every entry MUST have at least one tag. Use kebab-case exclusively.

- _Activity_: \`session-summary\`, \`certification\`, \`stress-test\`, \`bug-fix\`, \`release\`, \`audit\`, \`remediation\`, \`refactor\`
- _Domain_: \`security\`, \`performance\`, \`architecture\`, \`code-mode\`, \`documentation\`, \`ci-cd\`, \`github-integration\`
- _Tool group_: Name of the tool group being worked on (e.g., \`core\`, \`search\`, \`github\`, \`admin\`)
- _Pattern_: \`split-schema\`, \`zod\`, \`error-handling\`, \`dual-schema\`

### Significance Marking

Mark important entries with \`significance_type\`:

- \`release\` — Version deployments
- \`milestone\` — Major completions (full certification, security audit, feature launch)
- \`decision\` — Technology or process decisions
- \`architecture\` — Architecture decisions, pattern adoptions, structural changes
- \`blocker_resolved\` — Critical blockers that were resolved
- \`lesson_learned\` — Documented lessons from failures or unexpected outcomes
- \`breakthrough\` — Significant technical or conceptual breakthroughs
- \`security\` — Security audit completions, vulnerability remediations, hardening milestones

Do NOT mark routine session summaries or pass-only testing results as significant.

### Link Entries

Create relationships to build traversable context chains:

- \`implements\` — implementation→spec, remediation→audit findings
- \`resolved\` — bugfix→issue that reported the bug
- \`evolves_from\` — v2→v1, new iteration→prior version
- \`references\` — cross-project parity work, related entries
- \`clarifies\` — documentation→implementation it explains
- \`response_to\` — reply to a question or issue raised in another entry
- \`blocked_by\` — entry was blocked by another (blocker→resolution)
- \`caused\` — entry caused or led to another outcome

Only link truly related entries. Do NOT create bulk relationships between unrelated entries that happen to share tags.`

/**
 * Code Mode summary — only included when codemode group is enabled.
 * Points to memory://help/codemode for full API reference.
 */
const CODE_MODE_INSTRUCTIONS = `

## Code Mode

API: \`tool_name\` → \`mj.group.action()\` (e.g., \`search_entries\` → \`mj.search.searchEntries()\`)
Top-level: \`mj.core.create()\`, \`mj.core.recent()\`, \`mj.search.searchEntries()\`, etc.
Positional: \`create("note")\`, \`searchEntries("performance")\`
Discovery: \`mj.help()\` → \`{groups, totalMethods}\`. \`mj.core.help()\` for group-specific.
Sandbox: No \`setTimeout\`, \`setInterval\`, \`fetch\`, or network access.
Read \`memory://help/codemode\` for full namespace table, examples, and patterns.
**Codemode-only**: When \`mj_execute_code\` is the only registered tool, all tool names referenced in these instructions (e.g., \`create_entry\`, \`search_entries\`) must be called via \`mj_execute_code\` using \`mj.*\` namespaces. Do NOT call them as direct MCP tools.`

/**
 * All help keys that have content (for dynamic help pointer generation).
 */
const HELP_GROUP_KEYS: readonly string[] = ["github","hush-protocol","skills"]

/**
 * Build dynamic help pointers listing only the enabled groups.
 */
function buildHelpPointers(groups: Set<ToolGroup>): string {
    const enabledHelpGroups = HELP_GROUP_KEYS.filter((k) => groups.has(k as ToolGroup))
    if (enabledHelpGroups.length === 0) {
        return '\n\nRead `memory://help` for gotchas and critical usage patterns.'
    }
    return '\n\n## Available Help\n\n' +
        'Read `memory://help` for gotchas and critical usage patterns.\n' +
        'Read `memory://help/{group}` for: ' + enabledHelpGroups.join(', ') + '.'
}

/**
 * Build active groups summary listing enabled group names with tool counts.
 */
function buildActiveGroupsSummary(enabledTools: Set<string>): string {
    const activeGroups: { group: ToolGroup; tools: string[] }[] = []

    for (const [group, allTools] of Object.entries(TOOL_GROUPS) as [ToolGroup, string[]][]) {
        const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool))
        if (enabledInGroup.length > 0) {
            activeGroups.push({ group, tools: enabledInGroup })
        }
    }

    if (activeGroups.length === 0) return ''

    let summary = `\n\n## Active Tools (${String(enabledTools.size)})\n`
    for (const { group, tools } of activeGroups) {
        summary += `**${group}**: ${tools.map((t) => `\`${t}\``).join(', ')}\n`
    }
    return summary
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Generate dynamic instructions based on enabled tool groups and instruction level.
 *
 * Sections are conditionally included based on which tool groups are enabled:
 * - Code Mode snippet → only with `codemode` group
 * - Help group listing → `standard`+ level, only lists enabled groups
 * - Active tools summary → `full` level only
 * - Prompts listing → `full` level only
 *
 * @param enabledTools - Set of enabled tool names
 * @param prompts - Available prompt definitions
 * @param latestEntry - Optional latest entry for context snapshot
 * @param level - Instruction detail level (default: 'standard')
 * @param enabledGroups - Optional pre-computed enabled groups; derived from enabledTools if omitted
 */
export function generateInstructions(
    enabledTools: Set<string>,
    prompts: PromptDefinition[],
    latestEntry?: LatestEntrySnapshot,
    level: InstructionLevel = 'standard',
    enabledGroups?: Set<ToolGroup>
): string {
    // Derive enabled groups from enabled tools if not provided (backward compat)
    const groups = enabledGroups ?? getEnabledGroups(enabledTools)

    // Always start with core instructions (overview + behaviors)
    let instructions = CORE_INSTRUCTIONS

    // Code Mode snippet — only when codemode group is enabled
    if (groups.has('codemode')) {
        instructions += CODE_MODE_INSTRUCTIONS
    }

    // Add latest entry snapshot for immediate context (compact format)
    if (latestEntry) {
        const preview = latestEntry.content.slice(0, 120)
        instructions += `\n**Latest**: #${String(latestEntry.id)} (${latestEntry.timestamp}) ${latestEntry.entryType}\n> ${preview}${latestEntry.content.length > 120 ? '...' : ''}\n`
    }

    // Essential: minimal help pointer (no group listing)
    // Standard+: dynamic help pointers listing enabled groups
    if (level === 'essential') {
        instructions += '\n\nRead `memory://help` for gotchas and critical usage patterns.'
    } else {
        instructions += buildHelpPointers(groups)
    }

    // Full level includes active groups summary + prompts
    if (level === 'full') {
        instructions += buildActiveGroupsSummary(enabledTools)

        // Add prompts section
        if (prompts.length > 0) {
            instructions += `\n## Prompts (${String(prompts.length)})\n`
            instructions += 'Pre-built templates and guided workflows:\n'
            for (const prompt of prompts) {
                instructions += `- \`${prompt.name}\` - ${prompt.description ?? ''}\n`
            }
        }
    }

    return instructions
}

/**
 * Static instructions for backward compatibility.
 * @deprecated Use generateInstructions() instead for dynamic content
 */
export const SERVER_INSTRUCTIONS = CORE_INSTRUCTIONS

/**
 * Help content keyed by group name.
 * 'gotchas' is the always-available help (memory://help).
 * Other keys are feature-specific help (memory://help/{key}).
 */
export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([
  ["github", `# GitHub Integration

- Include \`issue_number\`/\`pr_number\` in \`create_entry\` to auto-link
- After closing issue/merging PR → create summary entry with learnings
- CI failures → \`actions-failure-digest\` prompt or \`memory://actions/recent\`
- Kanban: \`get_kanban_board\` → \`add_kanban_item\` / \`move_kanban_item\` / \`delete_kanban_item\` → document completion (project_number auto-resolves if repo is registered)
- Milestones: \`get_github_milestones\` → track project progress, \`memory://github/milestones\`
- **Project Initialization**: To register a new project workspace, create an entry with \`project_number: N\`. Instruct the user to manually update their \`PROJECT_REGISTRY\` config, as agents cannot directly edit protected IDE config files.
- **Multi-Project Routing**: If \`memory://briefing\` shows "Registered Workspaces":
  - **Tools**: Pass a \`repo\` parameter to ALL GitHub tools (including \`get_github_context\`) to explicitly target a specific project.
  - **Resources**: You MUST use the dynamic \`{repo}\` variants for resources (e.g., \`memory://github/status/{repo}\`, \`memory://github/insights/{repo}\`) rather than the base URI (\`memory://github/status\`), which will fail with a detection error.
  - **Dynamic Briefings**: You can explicitly request the briefing for a specific project by reading \`memory://briefing/{repo}\` instead of the global \`memory://briefing\` resource.

## Copilot Review Patterns

When the user has GitHub Copilot code review enabled:

**Learn from reviews** — After a PR is merged or reviewed, use \`get_copilot_reviews({ pr_number, repo })\` to read Copilot's findings (pass \`repo\` in multi-project setups). If patterns emerge (e.g., repeated null check warnings, missing error handling), suggest adding a rule or updating existing rules. Create journal entries tagged \`copilot-finding\` and link to the PR via \`pr_number\`.

**Pre-emptive checking** — Before creating or modifying code, search journal entries with tag \`copilot-finding\` for patterns relevant to the current work. Apply those patterns proactively to reduce review cycles.`],
  ["hush-protocol", `# Hush Protocol (Team Flags)

Flags are machine-actionable signals stored in the team database. They replace Slack/Teams noise with structured, searchable entries that surface automatically in the briefing.

**When to create a flag** (\`team_pass_flag\` — accepts \`flag_type\`, \`message\`, and optional \`target_user\`, \`link\`, \`project_number\`, \`issue_number\`):

- \`blocker\` — work is blocked and requires another person's action
- \`needs_review\` — code, document, or decision needs peer review
- \`help_requested\` — stuck and need guidance or pairing
- \`fyi\` — non-blocking awareness signal (completed migration, config change, etc.)

**When to resolve** (\`team_resolve_flag\`): After the blocking condition is cleared. Include a brief resolution comment describing what was done. Resolving is idempotent — safe to call on already-resolved flags.

**Briefing integration**: The \`memory://briefing\` payload includes \`activeFlags\` when unresolved flags exist. The user's agent rules may instruct you to render these prominently. Always check for and acknowledge active flags at session start.

**Dashboard**: Read \`memory://flags\` to see all active (unresolved) flags. Read \`memory://flags/vocabulary\` to see the configured flag types.

**Code Mode**: \`mj.team.passTeamFlag({ flag_type, message, target_user })\` and \`mj.team.resolveTeamFlag({ flag_id })\`.`],
  ["skills", `# Rule & Skill Suggestions

When you notice the user consistently applies patterns, preferences, or workflows that could be codified:

**Suggest adding a rule** when you observe:

- Naming conventions, formatting preferences, or coding standards
- Testing patterns or verification steps the user always follows
- Project-specific commands, workflows, or deployment steps
- Error handling patterns or logging conventions

**Suggest adding a skill** when you build:

- Reusable multi-step processes (e.g., deployment, release, audit workflows)
- Project-specific templates or scaffolds
- Complex integrations or tool chains the user may repeat

**Suggest refining existing rules/skills** when you notice:

- A rule conflict or ambiguity causing inconsistent behavior
- An outdated pattern that no longer matches the codebase
- Missing edge cases or exceptions to an existing rule
- A skill that could be extended with new steps

**How to act:**

- The briefing shows **Rules** and **Skills** paths — use these to locate the files
- **Always ask the user first** — never create or modify rules/skills silently
- Frame suggestions as: "I noticed you always [pattern]. Would you like me to add/update a rule for this?"
- For skills, explain the workflow it would automate and what triggers it

## Native Agent Skills (NPM Distribution)

This server leverages the \`neverinfamous-agent-skills\` package. If the user's \`SKILLS_DIR_PATH\` environment variable targets these, you have native access to skills covering TypeScript, React, Playwright, Go, Rust, Python, Docker, Tailwind CSS, shadcn/ui, security auditing, MCP server development, and DevOps workflows (\`issue-triage\`, \`pr-review\`, \`github-actions\`, \`copilot-audit\`, etc.). The \`adversarial-planner\` skill provides multi-pass plan review with structured critique stages.

- The user can distribute or update these skills across their repositories by running \`npx neverinfamous-agent-skills@latest\`.
- If you need to create a new skill, reference the bundled \`skill-builder\` instructions!`],
])
