/**
 * Server instructions for Memory Journal MCP.
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions.md instead,
 *     then run: npm run generate:instructions
 *
 * These instructions are automatically sent to MCP clients during initialization,
 * providing guidance for AI agents on tool usage.
 *
 * Tool parameter reference is served dynamically via memory://help/{group}.
 * Field notes and gotchas are served via memory://help/gotchas.
 *
 * Optimized for token efficiency with tiered instruction levels.
 * Sections are conditionally included based on enabled tool groups.
 */

import type { ToolGroup } from '../types/index.js'
import { TOOL_GROUPS, getEnabledGroups } from '../filtering/tool-filter.js'

/**
 * Resource definition for instruction generation
 */
export interface ResourceDefinition {
    uri: string
    name: string
    description?: string
}

/**
 * Prompt definition for instruction generation
 */
export interface PromptDefinition {
    name: string
    description?: string
}

/**
 * Latest entry snapshot for initial briefing
 */
export interface LatestEntrySnapshot {
    id: number
    timestamp: string
    entryType: string
    content: string
}

/**
 * Instruction detail level for token efficiency
 * - essential: ~200 tokens - Core behaviors only (for token-constrained clients)
 * - standard: ~350 tokens - + GitHub patterns + help pointers
 * - full: ~400 tokens - + active tools/prompts summary
 */
export type InstructionLevel = 'essential' | 'standard' | 'full'

// =============================================================================
// Composable Instruction Segments
// =============================================================================

/**
 * Core behavioral guidance — always included regardless of enabled groups.
 * Session Start, Behaviors, Rule & Skill Suggestions.
 */
const CORE_INSTRUCTIONS = `# memory-journal-mcp

## Session Start

**ESSENTIAL**: Before processing any user request at the start of a chat, you MUST read the \`memory://briefing/{repo_name}\`. **Use the standard MCP \`read_resource\` tool for this (do NOT use Code Mode/execute_code).** Infer the \`repo_name\` from the user's prompt or your active workspace context. Once read, present the \`userMessage\` from the briefing to the user as a formatted bullet list containing the key facts for all available fields including:

- Project Name:
- Entry counts (journal + team)
- Latest Entry (journal + team):
- GitHub: repo, branch, CI status, open issues/PRs, insights
- Milestone progress (if any)
- Template resources count
- Registered Workspaces (if available - provides automatic repo-to-project routing)
- Optional metadata present (rulesFile, skillsDir, workflowSummary, copilotReviews, Team DB)

- **AntiGravity**: Tools are \`mcp_{name}_{tool}\` → server name = \`memory-journal-mcp\`
- **Cursor**: Tools are \`user-{name}-{tool}\` → server name = \`user-memory-journal-mcp\`
- **Other clients**: Use configured name exactly. Use tool-prefix discovery if unsure.

## Behaviors

### memory-journal-mcp Behaviors

- **Personal vs Team**: **ALWAYS use the personal journal** (e.g., \`create_entry\`) by default. ONLY save to the team journal (e.g., \`team_create_entry\`) if the user explicitly requests it.
- **Create entries for**: implementations, decisions, bug fixes, milestones, user requests to "remember"
- **Search before**: major decisions, referencing prior work, understanding project context
- **Analyze insights**: Use cross-project insights (\`get_cross_project_insights\`) before defining architectures or cross-cutting abstractions. Use repo insights (\`memory://github/insights\`) to gauge traction.
- **Link entries**: implementation→spec, bugfix→issue, followup→prior work

### Rule & Skill Suggestions

When you notice the user consistently applies patterns, preferences, or workflows that could be codified:

**Suggest adding a rule** when you observe:

- Naming conventions, formatting preferences, or coding standards
- Testing patterns or verification steps the user always follows
- Project-specific commands, workflows, or deployment steps
- Error handling patterns or logging conventions

**Suggest adding a skill** when you build:

- Reusable multi-step processes (e.g., deployment, release, audit workflows)
- Project-specific templates or scaffolds
- Complex integrations or tool chains the user may repeat

**Suggest refining existing rules/skills** when you notice:

- A rule conflict or ambiguity causing inconsistent behavior
- An outdated pattern that no longer matches the codebase
- Missing edge cases or exceptions to an existing rule
- A skill that could be extended with new steps

**How to act:**

- The briefing shows **Rules** and **Skills** paths — use these to locate the files
- **Always ask the user first** — never create or modify rules/skills silently
- Frame suggestions as: "I noticed you always [pattern]. Would you like me to add/update a rule for this?"
- For skills, explain the workflow it would automate and what triggers it
`

/**
 * Copilot Review Patterns — only when `github` group is enabled.
 * References `get_copilot_reviews` which is a GitHub tool.
 */
const COPILOT_REVIEW_INSTRUCTIONS = `\n## Copilot Review Patterns

When the user has GitHub Copilot code review enabled:

**Learn from reviews** — After a PR is merged or reviewed, use \`get_copilot_reviews(pr_number)\` to read Copilot's findings. If patterns emerge (e.g., repeated null check warnings, missing error handling), suggest adding a rule or updating existing rules. Create journal entries tagged \`copilot-finding\` and link to the PR via \`pr_number\`.

**Pre-emptive checking** — Before creating or modifying code, search journal entries with tag \`copilot-finding\` for patterns relevant to the current work. Apply those patterns proactively to reduce review cycles.

**How to act:**

- The briefing shows **Rules** and **Skills** paths — use these to locate the files
- **Always ask the user first** — never create or modify rules/skills silently
- Frame suggestions as: "I noticed you always [pattern]. Would you like me to add/update a rule for this?"
- For skills, explain the workflow it would automate and what triggers it
`

/**
 * Quick Access table — always included.
 * The semantic_search row is conditional on the `search` group.
 */
function buildQuickAccess(groups: Set<ToolGroup>): string {
    let table = `
## Quick Access

| Purpose         | Action                      |
| --------------- | --------------------------- |
| Session context | \`memory://briefing\`         |
| Recent entries  | \`memory://recent\`           |
| Health/time     | \`memory://health\`           |
`
    if (groups.has('search')) {
        table += `| Semantic search | \`semantic_search(query)\`    |
`
    }
    table += `| Full context    | \`get-context-bundle\` prompt |
`
    return table
}

/**
 * Code Mode namespace row definitions.
 * Each maps a tool group to its Code Mode API namespace.
 */
const CODE_MODE_NAMESPACE_ROWS: { group: ToolGroup; label: string; namespace: string; example: string }[] = [
    { group: 'core', label: 'Core', namespace: '`mj.core.*`', example: '`mj.core.createEntry("Implemented feature X")`' },
    { group: 'search', label: 'Search', namespace: '`mj.search.*`', example: '`mj.search.searchEntries("performance")`' },
    { group: 'analytics', label: 'Analytics', namespace: '`mj.analytics.*`', example: '`mj.analytics.getStatistics()`' },
    { group: 'relationships', label: 'Relationships', namespace: '`mj.relationships.*`', example: '`mj.relationships.linkEntries(1, 2, "implements")`' },
    { group: 'export', label: 'Export', namespace: '`mj.export.*`', example: '`mj.export.exportEntries("json")`' },
    { group: 'admin', label: 'Admin', namespace: '`mj.admin.*`', example: '`mj.admin.rebuildVectorIndex()`' },
    { group: 'github', label: 'GitHub', namespace: '`mj.github.*`', example: '`mj.github.getGithubIssues({ state: "open" })`' },
    { group: 'backup', label: 'Backup', namespace: '`mj.backup.*`', example: '`mj.backup.backupJournal()`' },
    { group: 'team', label: 'Team', namespace: '`mj.team.*`', example: '`mj.team.teamCreateEntry("Team update")`' },
]

/**
 * Code Mode section — only when `codemode` group is enabled.
 * The namespace table dynamically omits rows for disabled groups.
 * The behavioral text (await patterns, readonly, return shape) comes from the .md source.
 */
function buildCodeModeInstructions(groups: Set<ToolGroup>): string {
    // Build namespace table with only enabled groups
    const rows = CODE_MODE_NAMESPACE_ROWS
        .filter((r) => groups.has(r.group))
        .map((r) => `| ${r.label.padEnd(13)} | ${r.namespace.padEnd(20)} | ${r.example.padEnd(50)} |`)
        .join('\n')

    // Build the static behavioral text from the .md source,
    // but replace the full namespace table with the filtered version
    const fullSection = CODE_MODE_FULL_TEXT
    const tableStart = fullSection.indexOf('| Group')
    const tableEnd = fullSection.indexOf('\n\n**Features**')
    if (tableStart === -1 || tableEnd === -1) {
        // Fallback: return full section if markers not found
        return '\n' + fullSection
    }
    const beforeTable = fullSection.slice(0, tableStart)
    const headerLine = '| Group         | Namespace            | Example                                            |'
    const separatorLine = '| ------------- | -------------------- | -------------------------------------------------- |'
    const afterTable = fullSection.slice(tableEnd)
    return '\n' + beforeTable + headerLine + '\n' + separatorLine + '\n' + rows + afterTable
}

/**
 * Full Code Mode section text from .md source (used as template for filtered version)
 */
const CODE_MODE_FULL_TEXT = `## Code Mode (Token-Efficient Multi-Step Operations)

For multi-step workflows (3+ operations), prefer \`mj_execute_code\` over individual tool calls.
This executes JavaScript in a sandboxed environment with all tools available as \`mj.*\` API:

| Group         | Namespace            | Example                                            |
| ------------- | -------------------- | -------------------------------------------------- |
| Core          | \`mj.core.*\`          | \`mj.core.createEntry("Implemented feature X")\`     |
| Search        | \`mj.search.*\`        | \`mj.search.searchEntries("performance")\`           |
| Analytics     | \`mj.analytics.*\`     | \`mj.analytics.getStatistics()\`                     |
| Relationships | \`mj.relationships.*\` | \`mj.relationships.linkEntries(1, 2, "implements")\` |
| Export        | \`mj.export.*\`        | \`mj.export.exportEntries("json")\`                  |
| Admin         | \`mj.admin.*\`         | \`mj.admin.rebuildVectorIndex()\`                    |
| GitHub        | \`mj.github.*\`        | \`mj.github.getGithubIssues({ state: "open" })\`     |
| Backup        | \`mj.backup.*\`        | \`mj.backup.backupJournal()\`                        |
| Team          | \`mj.team.*\`          | \`mj.team.teamCreateEntry("Team update")\`           |

**Features**: Positional args (\`createEntry("note")\`), aliases (\`mj.core.create\`), \`mj.help()\` for discovery.
**Readonly mode**: \`readonly: true\` restricts to read-only tools only. Calling a mutation method (e.g., \`mj.core.create(...)\`) in readonly mode throws an error that halts execution — the sandbox returns \`{ success: false, error: "Operation '...' is not found in group" }\`. If a group has no methods at all (fully stripped), the error says \`"no methods (read-only mode?)"\`.
**Returns**: Last expression value. Errors return \`{ success: false, error: "..." }\`.

**GitHub Context Injection**: You can pass \`repo: 'my-repo'\` directly to \`mj_execute_code\` (e.g., \`mj_execute_code({ code, repo: 'memory-journal-mcp' })\`) to instantly bind that repository and its default Kanban board to all GitHub and Kanban tools running inside the sandbox, avoiding the need to pass \`owner\`/\`repo\` manually to individual methods inside.

**Important — all \`mj.*\` methods return Promises. Always \`await\` them:**

\`\`\`js
// ✅ Correct
const result = await mj.core.recent({ limit: 5 })
return result.entries.map((e) => e.id)

// ❌ Wrong — returns a Promise object, not the entries
const result = mj.core.recent({ limit: 5 })

// ✅ Discovery
const help = await mj.help() // { groups, totalMethods, usage }
const groupHelp = await mj.core.help() // { group, methods }
\`\`\`

**\`mj.core.recent()\` return shape**: Returns \`{ entries: JournalEntry[], count: number }\` — not a plain array. Access \`.entries\` to iterate:

\`\`\`js
const { entries, count } = await mj.core.recent({ limit: 10 })
return entries.map((e) => ({ id: e.id, content: e.content.slice(0, 50) }))
\`\`\`
`

/**
 * GitHub integration patterns (~150 additional tokens)
 * Only included when `github` group is enabled.
 */
const GITHUB_INSTRUCTIONS = `\n## GitHub Integration

- Include \`issue_number\`/\`pr_number\` in \`create_entry\` to auto-link
- After closing issue/merging PR → create summary entry with learnings
- CI failures → \`actions-failure-digest\` prompt or \`memory://actions/recent\`
- Kanban: \`get_kanban_board\` → \`move_kanban_item\` → document completion (project_number auto-resolves if repo is registered)
- Milestones: \`get_github_milestones\` → track project progress, \`memory://github/milestones\`
- **Multi-Project Routing**: If \`memory://briefing\` shows "Registered Workspaces":
  - **Tools**: Pass a \`repo\` parameter to ALL GitHub tools (including \`get_github_context\`) to explicitly target a specific project.
  - **Resources**: You MUST use the dynamic \`{repo}\` variants for resources (e.g., \`memory://github/status/{repo}\`, \`memory://github/insights/{repo}\`) rather than the base URI (\`memory://github/status\`), which will fail with a detection error.
  - **Dynamic Briefings**: You can explicitly request the briefing for a specific project by reading \`memory://briefing/{repo}\` instead of the global \`memory://briefing\` resource.
`

/**
 * Help resource pointers — directs agents to pull-based reference
 */
const HELP_POINTERS = `\n## Help Resources

Read \`memory://help\` for tool group index and available help resources.
Read \`memory://help/{group}\` for per-group tool reference (parameters, annotations, examples).
Read \`memory://help/gotchas\` for critical field notes and usage patterns.
Only help resources for your enabled tool groups are registered.
`

/**
 * Server access instructions - critical for AI agents to call tools correctly
 */
const SERVER_ACCESS_INSTRUCTIONS = `\n## How to Access This Server

### Server Name Discovery

The server name used for resource and tool calls depends on your MCP client:

- **AntiGravity**: Prefixes tools with \`mcp_\` and uses underscores. If the server is named \`memory-journal-mcp\` in config, tools appear as \`mcp_memory-journal-mcp_create_entry\`. Use \`memory-journal-mcp\` as the server name for resource calls.
- **Cursor**: Prepends \`user-\` to the configured name. If the server is named \`memory-journal-mcp\` in config, use \`user-memory-journal-mcp\` for \`ListMcpResources\` and \`FetchMcpResource\` calls.
- **Other clients** (Claude Desktop, etc.): Likely use the configured name exactly. Only Cursor and AntiGravity have been verified — use the tool-prefix discovery method if unsure.

To identify your server name: look at the tool name prefix. Strip the tool name suffix to get the server name. Examples: \`mcp_memory-journal-mcp_create_entry\` → \`memory-journal-mcp\`; \`user-memory-journal-mcp-create_entry\` → \`user-memory-journal-mcp\`.

### Calling Tools

Use the tool functions directly — they are already available in your context by their full prefixed name.

### Reading Resources

Use the resource-reading mechanism provided by your MCP client with the discovered server name and \`memory://\` URIs.

Do NOT try to browse filesystem paths for MCP tool/resource definitions — use the MCP protocol directly.

## Quick Health Check

Fetch \`memory://health\` to verify server status, database stats, and tool availability.
`

/**
 * Field notes and gotchas — served via memory://help/gotchas resource.
 * Exported so the help resource handler can access it.
 *
 * NOTE: This file is inlined verbatim by scripts/generate-server-instructions.ts
 * into src/constants/server-instructions.ts, which already imports TOOL_GROUPS.
 * Do NOT add import statements here — they would appear as raw text in the output.
 */
export const GOTCHAS_CONTENT = `# memory-journal-mcp — Field Notes & Gotchas

## ⚠️ Critical Patterns

- **\`autoContext\`**: Reserved for future automatic context capture. Currently always \`null\`.
- **\`memory://tags\` vs \`list_tags\`**: Resource includes \`id\`, \`name\`, \`count\`; tool returns only \`name\`, \`count\`. Neither returns orphan tags with zero usage.
- **Tag naming**: Use lowercase with dashes (e.g., \`bug-fix\`, \`phase-2\`). Use \`merge_tags\` to consolidate duplicates (e.g., merge \`phase2\` into \`phase-2\`).
- **\`merge_tags\` behavior**: Only updates non-deleted entries. Deleted entries retain their original tags.
- **\`prStatus\` in entries**: Reflects PR state at entry creation time, not current state. Use \`get_github_pr\` for live status.
- **\`restore_backup\` behavior**: Restores entire database state. Any recent changes (new entries, tag merges via \`merge_tags\`, relationships) are reverted. A pre-restore backup is automatically created for safety.

## Semantic Search

- **Indexing**: Entries are auto-indexed on creation (fire-and-forget). If index count drifts from DB count, use \`rebuild_vector_index\` or enable \`AUTO_REBUILD_INDEX=true\` for automatic reconciliation on server startup.
- **Thresholds**: Default similarity threshold is 0.25. For broader matches, try 0.15-0.2. Higher values (0.4+) return only very close semantic matches. A quality floor of 0.5 is always enforced: if all results score below 0.5, a hint is included indicating results may be noise. The \`hint_on_empty\` flag (default true) only controls advisory hints for empty indexes and zero-match queries — the quality gate hint is always shown.

## Search

- **\`search_entries\` FTS5 query syntax**: Uses FTS5 full-text search with Porter stemmer. Phrase queries: \`"error handling"\`. Prefix: \`auth*\`. Boolean: \`deploy OR release\`, \`error NOT warning\`. Word-boundary matching ("log" matches "log" but not "catalog"). Results ranked by BM25 relevance. Falls back to LIKE substring matching for queries with unbalanced quotes or special characters.

## Relationships & Analytics

- **Causal relationship types**: Use \`blocked_by\` (A was blocked by B), \`resolved\` (A resolved B), \`caused\` (A caused B) for decision tracing and failure analysis. Visualizations use distinct arrow styles for causal types.
- **Enhanced analytics**: \`get_statistics\` returns \`decisionDensity\` (significant entries per period), \`relationshipComplexity\` (avg relationships per entry), \`activityTrend\` (period-over-period growth %), and \`causalMetrics\` (counts for blocked_by/resolved/caused).
- **Importance scores**: \`get_entry_by_id\` returns \`importance\` (0.0-1.0) and \`importanceBreakdown\` showing weighted components: significance (30%), relationships (35%), causal (20%), recency (15%). \`memory://significant\` sorts entries by importance.
- **\`inactiveThresholdDays\`**: \`get_cross_project_insights\` includes \`inactiveThresholdDays: 7\` in output, documenting the inactive project classification cutoff.

## GitHub Metadata

- **GitHub metadata in entries**: Entry output includes 10 GitHub fields (\`issueNumber\`, \`issueUrl\`, \`prNumber\`, \`prUrl\`, \`prStatus\`, \`projectNumber\`, \`projectOwner\`, \`workflowRunId\`, \`workflowName\`, \`workflowStatus\`) in all tool responses.

## Entry Operations

- **\`delete_entry\` on soft-deleted**: \`delete_entry(id, permanent: true)\` works on previously soft-deleted entries. Returns \`success: false\` for nonexistent entries.

## Team Database

- **Team cross-database search**: \`search_entries\` and \`search_by_date_range\` automatically merge team DB results when \`TEAM_DB_PATH\` is configured. Results include a \`source\` field ("personal" or "team").
- **Team vector search**: Team has its own isolated vector index. Use \`team_rebuild_vector_index\` if the team index drifts. \`team_semantic_search\` works identically to personal \`semantic_search\`.
- **Team tools without \`TEAM_DB_PATH\`**: All ${TOOL_GROUPS.team.length} team tools return \`{ success: false, error: "Team collaboration is not configured..." }\` — no crash, no partial results.
`


/**
 * Generate dynamic instructions based on enabled tools, resources, prompts, and latest entry.
 *
 * Sections are conditionally included based on which tool groups are enabled:
 * - Copilot Review Patterns → only with `github` group
 * - Code Mode → only with `codemode` group (namespace table only lists enabled groups)
 * - GitHub Integration → only with `github` group (standard+ level)
 * - Quick Access semantic_search row → only with `search` group
 *
 * @param enabledTools - Set of enabled tool names
 * @param prompts - Available prompt definitions
 * @param latestEntry - Optional latest entry for context snapshot
 * @param level - Instruction detail level (default: 'standard')
 * @param enabledGroups - Optional pre-computed enabled groups; derived from enabledTools if omitted
 */
export function generateInstructions(
    enabledTools: Set<string>,
    prompts: PromptDefinition[],
    latestEntry?: LatestEntrySnapshot,
    level: InstructionLevel = 'standard',
    enabledGroups?: Set<ToolGroup>
): string {
    // Derive enabled groups from enabled tools if not provided (backward compat)
    const groups = enabledGroups ?? getEnabledGroups(enabledTools)

    // Always start with core behavioral guidance
    let instructions = CORE_INSTRUCTIONS

    // Copilot Review Patterns — only when github group is enabled
    if (groups.has('github')) {
        instructions += COPILOT_REVIEW_INSTRUCTIONS
    }

    // Quick Access — always, but semantic_search row conditional on search group
    instructions += buildQuickAccess(groups)

    // Code Mode — only when codemode group is enabled
    if (groups.has('codemode')) {
        instructions += buildCodeModeInstructions(groups)
    }

    // Add latest entry snapshot for immediate context (compact format)
    if (latestEntry) {
        const preview = latestEntry.content.slice(0, 120)
        instructions += `\n**Latest**: #${String(latestEntry.id)} (${latestEntry.timestamp}) ${latestEntry.entryType}\n> ${preview}${latestEntry.content.length > 120 ? '...' : ''}\n`
    }

    // Standard and full levels include GitHub patterns + help pointers
    if (level === 'standard' || level === 'full') {
        if (groups.has('github')) {
            instructions += GITHUB_INSTRUCTIONS
        }
        instructions += HELP_POINTERS
    }

    // Full level includes server access instructions + active tools/prompts summary
    if (level === 'full') {
        instructions += SERVER_ACCESS_INSTRUCTIONS

        // Add active tools summary
        const activeGroups = getActiveToolGroups(enabledTools)
        if (activeGroups.length > 0) {
            instructions += `\n## Active Tools (${String(enabledTools.size)})\n`
            for (const { group, tools } of activeGroups) {
                instructions += `**${group}**: ${tools.map((t) => `\`${t}\``).join(', ')}\n`
            }
        }

        // Add prompts section
        if (prompts.length > 0) {
            instructions += `\n## Prompts (${String(prompts.length)})\n`
            instructions += 'Pre-built templates and guided workflows:\n'
            for (const prompt of prompts) {
                instructions += `- \`${prompt.name}\` - ${prompt.description ?? ''}\n`
            }
        }
    }

    return instructions
}

/**
 * Get active tool groups with their enabled tools
 */
function getActiveToolGroups(enabledTools: Set<string>): { group: ToolGroup; tools: string[] }[] {
    const activeGroups: { group: ToolGroup; tools: string[] }[] = []

    for (const [group, allTools] of Object.entries(TOOL_GROUPS) as [ToolGroup, string[]][]) {
        const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool))
        if (enabledInGroup.length > 0) {
            activeGroups.push({ group, tools: enabledInGroup })
        }
    }

    return activeGroups
}

/**
 * Static instructions for backward compatibility
 * @deprecated Use generateInstructions() instead for dynamic content
 */
export const SERVER_INSTRUCTIONS =
    CORE_INSTRUCTIONS +
    COPILOT_REVIEW_INSTRUCTIONS +
    buildQuickAccess(new Set(Object.keys(TOOL_GROUPS) as ToolGroup[])) +
    buildCodeModeInstructions(new Set(Object.keys(TOOL_GROUPS) as ToolGroup[])) +
    GITHUB_INSTRUCTIONS

