/**
 * Server instructions for Memory Journal MCP.
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions.md instead,
 *     then run: npm run generate:instructions
 *
 * These instructions are automatically sent to MCP clients during initialization,
 * providing guidance for AI agents on tool usage.
 *
 * Optimized for token efficiency with tiered instruction levels.
 */

import type { ToolGroup } from '../types/index.js'
import { TOOL_GROUPS } from '../filtering/ToolFilter.js'

/**
 * Resource definition for instruction generation
 */
export interface ResourceDefinition {
    uri: string
    name: string
    description?: string
}

/**
 * Prompt definition for instruction generation
 */
export interface PromptDefinition {
    name: string
    description?: string
}

/**
 * Latest entry snapshot for initial briefing
 */
export interface LatestEntrySnapshot {
    id: number
    timestamp: string
    entryType: string
    content: string
}

/**
 * Instruction detail level for token efficiency
 * - essential: ~200 tokens - Core behaviors only (for token-constrained clients)
 * - standard: ~400 tokens - + GitHub patterns (default)
 * - full: ~600 tokens - + tool/resource listings
 */
export type InstructionLevel = 'essential' | 'standard' | 'full'

/**
 * Essential behavioral guidance (~200 tokens)
 * Core patterns every AI agent should follow.
 */
const ESSENTIAL_INSTRUCTIONS = `# memory-journal-mcp

## Session Start

1. Read \`memory://briefing\` for project context
   - **Server name for resource calls**: Derive from tool prefixes — strip the tool name suffix to get the server name.
     - **AntiGravity**: Tools are \`mcp_{name}_{tool}\` (e.g., \`mcp_memory-journal-mcp_create_entry\`). Server name = \`memory-journal-mcp\`.
     - **Cursor**: Tools are \`user-{name}-{tool}\` (e.g., \`user-memory-journal-mcp-create_entry\`). Server name = \`user-memory-journal-mcp\`.
     - **Other clients** (Claude Desktop, etc.): Likely use the configured name exactly (e.g., \`memory-journal-mcp\`). Only Cursor and AntiGravity have been verified — use the tool-prefix discovery method above if unsure.
2. **Show the \`userMessage\` to the user** (it contains a formatted summary of project context)
3. Proceed with the user's request

## Behaviors

- **Create entries for**: implementations, decisions, bug fixes, milestones, user requests to "remember"
- **Search before**: major decisions, referencing prior work, understanding project context
- **Link entries**: implementation→spec, bugfix→issue, followup→prior work

## Rule & Skill Suggestions

When you notice the user consistently applies patterns, preferences, or workflows that could be codified:

- **Offer to create a rule or skill** — always ask the user first, never create silently
- Examples: coding conventions, testing patterns, deployment steps, project-specific commands
- Frame it as: "I noticed you always [pattern]. Would you like me to save this as a rule/skill so future agents follow it automatically?"

## Quick Access

| Purpose         | Action                      |
| --------------- | --------------------------- |
| Session context | \`memory://briefing\`         |
| Recent entries  | \`memory://recent\`           |
| Health/time     | \`memory://health\`           |
| Semantic search | \`semantic_search(query)\`    |
| Full context    | \`get-context-bundle\` prompt |
`

/**
 * GitHub integration patterns (~150 additional tokens)
 */
const GITHUB_INSTRUCTIONS = `
## GitHub Integration

- Include \`issue_number\`/\`pr_number\` in \`create_entry\` to auto-link
- After closing issue/merging PR → create summary entry with learnings
- CI failures → \`actions-failure-digest\` prompt or \`memory://actions/recent\`
- Kanban: \`get_kanban_board(project_number)\` → \`move_kanban_item\` → document completion
- Milestones: \`get_github_milestones\` → track project progress, \`memory://github/milestones\`
- GitHub tools auto-detect owner/repo from git context; specify explicitly if null
`

/**
 * Server access instructions - critical for AI agents to call tools correctly
 */
const SERVER_ACCESS_INSTRUCTIONS = `
## How to Access This Server

### Server Name Discovery

The server name used for resource and tool calls depends on your MCP client:

- **AntiGravity**: Prefixes tools with \`mcp_\` and uses underscores. If the server is named \`memory-journal-mcp\` in config, tools appear as \`mcp_memory-journal-mcp_create_entry\`. Use \`memory-journal-mcp\` as the server name for resource calls.
- **Cursor**: Prepends \`user-\` to the configured name. If the server is named \`memory-journal-mcp\` in config, use \`user-memory-journal-mcp\` for \`ListMcpResources\` and \`FetchMcpResource\` calls.
- **Other clients** (Claude Desktop, etc.): Likely use the configured name exactly. Only Cursor and AntiGravity have been verified — use the tool-prefix discovery method if unsure.

To identify your server name: look at the tool name prefix. Strip the tool name suffix to get the server name. Examples: \`mcp_memory-journal-mcp_create_entry\` → \`memory-journal-mcp\`; \`user-memory-journal-mcp-create_entry\` → \`user-memory-journal-mcp\`.

### Calling Tools

Use the tool functions directly — they are already available in your context by their full prefixed name.

### Reading Resources

Use the resource-reading mechanism provided by your MCP client with the discovered server name and \`memory://\` URIs.

Do NOT try to browse filesystem paths for MCP tool/resource definitions — use the MCP protocol directly.

## Quick Health Check

Fetch \`memory://health\` to verify server status, database stats, and tool availability.
`

/**
 * Tool parameter reference - essential for correct tool invocation
 */
const TOOL_PARAMETER_REFERENCE = `
## Tool Parameter Reference

### Entry Operations

| Tool                   | Required Parameters | Optional Parameters                                                                                                                                                                                                                         |
| ---------------------- | ------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \`create_entry\`         | \`content\` (string)  | \`entry_type\`, \`tags\` (array), \`is_personal\`, \`significance_type\`, \`auto_context\`, \`issue_number\`, \`issue_url\`, \`pr_number\`, \`pr_url\`, \`pr_status\`, \`project_number\`, \`project_owner\`, \`workflow_run_id\`, \`workflow_name\`, \`workflow_status\` |
| \`create_entry_minimal\` | \`content\` (string)  | none                                                                                                                                                                                                                                        |
| \`get_entry_by_id\`      | \`entry_id\` (number) | \`include_relationships\` (bool, default true)                                                                                                                                                                                                |
| \`get_recent_entries\`   | none                | \`limit\` (default 5), \`is_personal\` (bool)                                                                                                                                                                                                   |
| \`update_entry\`         | \`entry_id\` (number) | \`content\`, \`tags\`, \`entry_type\`, \`is_personal\`                                                                                                                                                                                              |
| \`delete_entry\`         | \`entry_id\` (number) | \`permanent\` (bool, default false)                                                                                                                                                                                                           |
| \`list_tags\`            | none                | none                                                                                                                                                                                                                                        |

### Search Tools

| Tool                     | Required Parameters                   | Optional Parameters                                                                                            |
| ------------------------ | ------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| \`search_entries\`         | none                                  | \`query\`, \`limit\`, \`is_personal\`, \`issue_number\`, \`pr_number\`, \`pr_status\`, \`project_number\`, \`workflow_run_id\` |
| \`search_by_date_range\`   | \`start_date\`, \`end_date\` (YYYY-MM-DD) | \`tags\`, \`entry_type\`, \`is_personal\`, \`issue_number\`, \`pr_number\`, \`project_number\`, \`workflow_run_id\`          |
| \`semantic_search\`        | \`query\` (string)                      | \`limit\`, \`similarity_threshold\` (default 0.25), \`is_personal\`, \`hint_on_empty\` (bool, default true)            |
| \`get_vector_index_stats\` | none                                  | none                                                                                                           |

### Relationship Tools

| Tool                      | Required Parameters                      | Notes                                                                                                                                      |
| ------------------------- | ---------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------ |
| \`link_entries\`            | \`from_entry_id\`, \`to_entry_id\` (numbers) | Types: \`evolves_from\`, \`references\`, \`implements\`, \`clarifies\`, \`response_to\`, \`blocked_by\`, \`resolved\`, \`caused\`. Optional \`description\`. |
| \`visualize_relationships\` | none                                     | Optional \`entry_id\`, \`tags\` (array), \`depth\` (1-3, default 2), \`limit\` (default 20). Returns Mermaid diagram.                              |

### GitHub Tools

| Tool                 | Required Parameters     | Notes                                                                                                                        |
| -------------------- | ----------------------- | ---------------------------------------------------------------------------------------------------------------------------- |
| \`get_github_context\` | none                    | Returns repo info, open issues/PRs. Only counts OPEN items.                                                                  |
| \`get_github_issues\`  | none                    | Optional \`state\` (open/closed/all), \`limit\`, \`owner\`, \`repo\`                                                                 |
| \`get_github_prs\`     | none                    | Optional \`state\`, \`limit\`, \`owner\`, \`repo\`                                                                                   |
| \`get_github_issue\`   | \`issue_number\` (number) | Optional \`owner\`, \`repo\`. Fetches single issue details.                                                                      |
| \`get_github_pr\`      | \`pr_number\` (number)    | Optional \`owner\`, \`repo\`. Fetches single PR details.                                                                         |
| \`get_repo_insights\`  | none                    | Optional \`sections\` (stars/traffic/referrers/paths/all, default "stars"), \`owner\`, \`repo\`. Requires push access for traffic. |

GitHub tools auto-detect owner/repo from GITHUB_REPO_PATH. If \`detectedOwner\`/\`detectedRepo\` are null in response, specify \`owner\` and \`repo\` parameters explicitly.

### Issue Lifecycle Tools

| Tool                             | Required Parameters     | Notes                                                                                                                                                    |
| -------------------------------- | ----------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \`create_github_issue_with_entry\` | \`title\` (string)        | Optional \`body\`, \`labels\` (array), \`assignees\` (array), \`project_number\`, \`initial_status\`, \`milestone_number\`, \`entry_content\`, \`tags\`, \`owner\`, \`repo\` |
| \`close_github_issue_with_entry\`  | \`issue_number\` (number) | Optional \`comment\`, \`resolution_notes\`, \`tags\`, \`move_to_done\` (bool), \`project_number\`, \`owner\`, \`repo\`                                                 |

### Kanban Tools (GitHub Projects v2)

| Tool               | Required Parameters                                            | Notes                                                                                                     |
| ------------------ | -------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- |
| \`get_kanban_board\` | \`project_number\` (number)                                      | Optional \`owner\`. Returns columns with items grouped by Status                                            |
| \`move_kanban_item\` | \`project_number\`, \`item_id\` (string), \`target_status\` (string) | Optional \`owner\`. \`item_id\` is the GraphQL node ID from board items. Status matching is case-insensitive. |

**Finding the right project**: User may have multiple projects. Use \`get_kanban_board\` with different project numbers (1, 2, 3...) to find the correct one by checking \`projectTitle\`.

**Default Status columns** (typical GitHub Projects v2):

- \`Backlog\` - Items not yet started
- \`Ready\` - Ready to be picked up
- \`In progress\` - Actively being worked on
- \`In review\` - In review
- \`Done\` - Completed

Note: Status columns are dynamic per project. The \`statusOptions\` in the response shows available statuses for that specific project.

Kanban resources:

- \`memory://kanban/{project_number}\` - JSON board data
- \`memory://kanban/{project_number}/diagram\` - Mermaid visualization

### Milestone Tools

| Tool                      | Required Parameters                 | Notes                                                                             |
| ------------------------- | ----------------------------------- | --------------------------------------------------------------------------------- |
| \`get_github_milestones\`   | none                                | Optional \`state\` (open/closed/all), \`limit\`, \`owner\`, \`repo\`                      |
| \`get_github_milestone\`    | \`milestone_number\` (number)         | Optional \`owner\`, \`repo\`. Single milestone with completion %.                     |
| \`create_github_milestone\` | \`title\` (string)                    | Optional \`description\`, \`due_on\` (YYYY-MM-DD), \`owner\`, \`repo\`                    |
| \`update_github_milestone\` | \`milestone_number\` (number)         | Optional \`title\`, \`description\`, \`due_on\`, \`state\` (open/closed), \`owner\`, \`repo\` |
| \`delete_github_milestone\` | \`milestone_number\`, \`confirm: true\` | Optional \`owner\`, \`repo\`. Permanent deletion.                                     |

Milestone resources:

- \`memory://github/milestones\` - Open milestones with completion %
- \`memory://milestones/{number}\` - Single milestone detail

### Admin Tools

| Tool                   | Required Parameters         | Notes                                                                        |
| ---------------------- | --------------------------- | ---------------------------------------------------------------------------- |
| \`backup_journal\`       | none                        | Optional \`name\` (custom backup name)                                         |
| \`list_backups\`         | none                        | Returns available backup files                                               |
| \`cleanup_backups\`      | none                        | Optional \`keep_count\` (default 5). Deletes old backups, keeps N most recent. |
| \`restore_backup\`       | \`filename\`, \`confirm: true\` | Creates auto-backup before restore                                           |
| \`add_to_vector_index\`  | \`entry_id\` (single number)  | Indexes one entry for semantic search                                        |
| \`rebuild_vector_index\` | none                        | Re-indexes all entries                                                       |

### Export Tools

| Tool             | Required Parameters | Notes                                                                                                     |
| ---------------- | ------------------- | --------------------------------------------------------------------------------------------------------- |
| \`export_entries\` | none                | Optional \`format\` (json/markdown), \`limit\` (default 100), \`tags\`, \`start_date\`, \`end_date\`, \`entry_types\` |

## Entry Types

Valid values for \`entry_type\` parameter:

- \`personal_reflection\` (default) - Personal thoughts and notes
- \`project_decision\` - Architectural and team decisions
- \`technical_achievement\` - Milestones and breakthroughs
- \`bug_fix\` - Bug fixes and resolutions
- \`feature_implementation\` - Feature builds and rollouts
- \`code_review\` - Code review notes
- \`meeting_notes\` - Meeting summaries
- \`learning\` - Learning and research insights
- \`research\` - Research and exploration
- \`planning\` - Planning sessions and roadmaps (\`create_github_issue_with_entry\` uses this type)
- \`retrospective\` - Sprint and project retrospectives
- \`standup\` - Daily standup notes
- \`technical_note\` - Technical notes and observations
- \`development_note\` - Development process notes
- \`enhancement\` - Enhancement tracking
- \`milestone\` - Milestone documentation
- \`system_integration_test\` - Integration test records
- \`test_entry\` - Test and scratch entries
- \`other\` - Miscellaneous

## Field Notes

- **\`autoContext\`**: Reserved for future automatic context capture. Currently always \`null\`.
- **\`memory://tags\` vs \`list_tags\`**: Resource includes \`id\`, \`name\`, \`count\`; tool returns only \`name\`, \`count\`. Neither returns orphan tags with zero usage.
- **Tag naming**: Use lowercase with dashes (e.g., \`bug-fix\`, \`phase-2\`). Use \`merge_tags\` to consolidate duplicates (e.g., merge \`phase2\` into \`phase-2\`).
- **\`merge_tags\` behavior**: Only updates non-deleted entries. Deleted entries retain their original tags.
- **\`prStatus\` in entries**: Reflects PR state at entry creation time, not current state. Use \`get_github_pr\` for live status.
- **\`restore_backup\` behavior**: Restores entire database state. Any recent changes (new entries, tag merges via \`merge_tags\`, relationships) are reverted. A pre-restore backup is automatically created for safety.
- **Semantic search indexing**: Entries are auto-indexed on creation (fire-and-forget). If index count drifts from DB count, use \`rebuild_vector_index\` or enable \`AUTO_REBUILD_INDEX=true\` for automatic reconciliation on server startup.
- **\`semantic_search\` thresholds**: Default similarity threshold is 0.25. For broader matches, try 0.15-0.2. Higher values (0.4+) return only very close semantic matches.
- **Causal relationship types**: Use \`blocked_by\` (A was blocked by B), \`resolved\` (A resolved B), \`caused\` (A caused B) for decision tracing and failure analysis. Visualizations use distinct arrow styles for causal types.
- **Enhanced analytics**: \`get_statistics\` returns \`decisionDensity\` (significant entries per period), \`relationshipComplexity\` (avg relationships per entry), \`activityTrend\` (period-over-period growth %), and \`causalMetrics\` (counts for blocked_by/resolved/caused).
- **Importance scores**: \`get_entry_by_id\` returns \`importance\` (0.0-1.0) and \`importanceBreakdown\` showing weighted components: significance (30%), relationships (35%), causal (20%), recency (15%). \`memory://significant\` sorts entries by importance.
- **\`inactiveThresholdDays\`**: \`get_cross_project_insights\` includes \`inactiveThresholdDays: 7\` in output, documenting the inactive project classification cutoff.
- **GitHub metadata in entries**: Entry output includes 10 GitHub fields (\`issueNumber\`, \`issueUrl\`, \`prNumber\`, \`prUrl\`, \`prStatus\`, \`projectNumber\`, \`projectOwner\`, \`workflowRunId\`, \`workflowName\`, \`workflowStatus\`) in all tool responses.
- **\`delete_entry\` on soft-deleted**: \`delete_entry(id, permanent: true)\` works on previously soft-deleted entries. Returns \`success: false\` for nonexistent entries.

## Key Resources

| URI                       | Description                                   |
| ------------------------- | --------------------------------------------- |
| \`memory://health\`         | Server health, DB stats, tool filter status   |
| \`memory://briefing\`       | Session context with userMessage to show user |
| \`memory://instructions\`   | Full server instructions and tool reference   |
| \`memory://statistics\`     | Entry counts by type and period               |
| \`memory://recent\`         | 10 most recent entries                        |
| \`memory://tags\`           | All tags with usage counts                    |
| \`memory://significant\`    | Entries sorted by importance score            |
| \`memory://graph/recent\`   | Mermaid diagram of recent relationships       |
| \`memory://graph/actions\`  | CI/CD narrative graph                         |
| \`memory://actions/recent\` | Recent workflow runs                          |

| \`memory://github/status\` | GitHub repo overview (CI, issues, PRs, milestones) |
| \`memory://github/milestones\` | Open milestones with completion % |
| \`memory://github/insights\` | Stars, forks, and 14-day traffic summary |
| \`memory://kanban/{n}\` | Kanban board for project number n |
| \`memory://kanban/{n}/diagram\` | Mermaid Kanban visualization |
| \`memory://milestones/{n}\` | Single milestone detail + progress |
| \`memory://projects/{n}/timeline\` | Project entries timeline |
| \`memory://issues/{n}/entries\` | Entries linked to issue n |
| \`memory://prs/{n}/entries\` | Entries linked to PR n |
| \`memory://prs/{n}/timeline\` | PR lifecycle and linked entries |
`

/**
 * Generate dynamic instructions based on enabled tools, resources, prompts, and latest entry
 *
 * @param enabledTools - Set of enabled tool names
 * @param resources - Available resource definitions
 * @param prompts - Available prompt definitions
 * @param latestEntry - Optional latest entry for context snapshot
 * @param level - Instruction detail level (default: 'standard')
 */
export function generateInstructions(
    enabledTools: Set<string>,
    _resources: ResourceDefinition[],
    prompts: PromptDefinition[],
    latestEntry?: LatestEntrySnapshot,
    level: InstructionLevel = 'standard'
): string {
    let instructions = ESSENTIAL_INSTRUCTIONS

    // Add latest entry snapshot for immediate context (compact format)
    if (latestEntry) {
        const preview = latestEntry.content.slice(0, 120)
        instructions += `\n**Latest**: #${String(latestEntry.id)} (${latestEntry.timestamp}) ${latestEntry.entryType}\n> ${preview}${latestEntry.content.length > 120 ? '...' : ''}\n`
    }

    // Standard and full levels include GitHub patterns
    if (level === 'standard' || level === 'full') {
        instructions += GITHUB_INSTRUCTIONS
    }

    // Full level includes server access instructions and tool parameter reference
    if (level === 'full') {
        instructions += SERVER_ACCESS_INSTRUCTIONS
        instructions += TOOL_PARAMETER_REFERENCE

        // Add active tools summary
        const activeGroups = getActiveToolGroups(enabledTools)
        if (activeGroups.length > 0) {
            instructions += `\n## Active Tools (${String(enabledTools.size)})\n`
            for (const { group, tools } of activeGroups) {
                instructions += `**${group}**: ${tools.map((t) => `\`${t}\``).join(', ')}\n`
            }
        }

        // Add prompts section
        if (prompts.length > 0) {
            instructions += `\n## Prompts (${String(prompts.length)})\n`
            instructions += 'Pre-built templates and guided workflows:\n'
            for (const prompt of prompts) {
                instructions += `- \`${prompt.name}\` - ${prompt.description ?? ''}\n`
            }
        }
    }

    return instructions
}

/**
 * Get active tool groups with their enabled tools
 */
function getActiveToolGroups(enabledTools: Set<string>): { group: ToolGroup; tools: string[] }[] {
    const activeGroups: { group: ToolGroup; tools: string[] }[] = []

    for (const [group, allTools] of Object.entries(TOOL_GROUPS) as [ToolGroup, string[]][]) {
        const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool))
        if (enabledInGroup.length > 0) {
            activeGroups.push({ group, tools: enabledInGroup })
        }
    }

    return activeGroups
}

/**
 * Static instructions for backward compatibility
 * @deprecated Use generateInstructions() instead for dynamic content
 */
export const SERVER_INSTRUCTIONS = ESSENTIAL_INSTRUCTIONS + GITHUB_INSTRUCTIONS

