/**
 * Generates src/constants/server-instructions.ts from per-group markdown files.
 *
 * Reads server-instructions/*.md, escapes for template literals, and wraps them
 * in a TypeScript module with:
 *   - HELP_CONTENT map (on-demand pull-based reference)
 *   - generateInstructions() function (composable, filter-aware instructions)
 *
 * Pattern: Matches db-mcp and postgres-mcp directory-per-group architecture.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const constantsDir = resolve(projectRoot, 'src/constants')
const helpDir = resolve(constantsDir, 'server-instructions')

/**
 * Escape content for use inside a JS/TS template literal.
 * Handles: backslashes, backticks, and template expressions (${).
 */
function escapeForTemplateLiteral(content: string): string {
    return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

// Read overview (slim instructions field content)
const overviewMd = readFileSync(resolve(helpDir, 'overview.md'), 'utf-8').trim()
const overviewEscaped = escapeForTemplateLiteral(overviewMd)

// Read all help files (everything except overview.md and README.md)
const helpFiles = readdirSync(helpDir)
    .filter((f) => f.endsWith('.md') && f !== 'overview.md' && f.toLowerCase() !== 'readme.md')
    .sort()

const helpEntries: { key: string; content: string }[] = []
for (const file of helpFiles) {
    const key = basename(file, '.md') // "gotchas", "codemode", "github", etc.
    const content = readFileSync(resolve(helpDir, file), 'utf-8').trim()
    helpEntries.push({ key, content })
}

// Identify group-specific help entries (everything except gotchas)
const helpGroupKeys = helpEntries.filter((e) => e.key !== 'gotchas').map((e) => e.key)

// Use backtick char for building string to avoid nesting issues
const BT = '`'

// Build the TypeScript file using string concatenation
const lines: string[] = []

lines.push('/**')
lines.push(' * Server instructions for Memory Journal MCP.')
lines.push(' *')
lines.push(' * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY')
lines.push(' *     Edit src/constants/server-instructions/*.md instead,')
lines.push(' *     then run: npm run generate:instructions')
lines.push(' *')
lines.push(' * Slim instructions are sent to MCP clients during initialization.')
lines.push(' * Detailed help is available on-demand via memory://help resources.')
lines.push(' * Instructions are dynamically generated based on enabled tool groups')
lines.push(' * and instruction level for token efficiency.')
lines.push(' */')
lines.push('')
lines.push("import type { ToolGroup } from '../types/index.js'")
lines.push("import { TOOL_GROUPS, getEnabledGroups } from '../filtering/tool-filter.js'")
lines.push('')
lines.push('/**')
lines.push(' * Resource definition for instruction generation')
lines.push(' */')
lines.push('export interface ResourceDefinition {')
lines.push('    uri: string')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Prompt definition for instruction generation')
lines.push(' */')
lines.push('export interface PromptDefinition {')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Latest entry snapshot for initial briefing')
lines.push(' */')
lines.push('export interface LatestEntrySnapshot {')
lines.push('    id: number')
lines.push('    timestamp: string')
lines.push('    entryType: string')
lines.push('    content: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Instruction detail level for token efficiency')
lines.push(
    ' * - essential: ~300 tokens - Core behaviors + quick access (for token-constrained clients)'
)
lines.push(' * - standard: ~350 tokens - + help pointers for enabled groups')
lines.push(' * - full: ~500 tokens - + active tools/prompts summary')
lines.push(' */')
lines.push("export type InstructionLevel = 'essential' | 'standard' | 'full'")
lines.push('')

// ==========================================================================
// Composable Instruction Segments
// ==========================================================================

lines.push('// =============================================================================')
lines.push('// Composable Instruction Segments')
lines.push('// =============================================================================')
lines.push('')
lines.push('/**')
lines.push(' * Core instructions — always included regardless of enabled groups.')
lines.push(' * Contains quick access, help pointers, and essential behavioral guidance.')
lines.push(' */')
lines.push('const CORE_INSTRUCTIONS = ' + BT + overviewEscaped + BT)
lines.push('')
lines.push('/**')
lines.push(' * Code Mode summary — only included when codemode group is enabled.')
lines.push(' * Points to memory://help/codemode for full API reference.')
lines.push(' */')
lines.push(
    'const CODE_MODE_INSTRUCTIONS = ' +
        BT +
        escapeForTemplateLiteral(
            [
                '',
                '',
                '## Code Mode',
                '',
                'API: `tool_name` → `mj.group.action()` (e.g., `search_entries` → `mj.search.searchEntries()`)',
                'Globals: `createEntry()`, `find()`, `recent()`, `searchEntries()`, `deleteEntry()`, `help()` work without the `mj.` prefix.',
                'Positional: `create("note")`, `searchEntries("performance")`',
                'Aliases: Common parameter names are auto-corrected (`text`→`content`, `entry`→`entry_id`, `q`→`query`, `tag`→`tags[]`).',
                'Discovery: `mj.help()` → `{groups, totalMethods}`. `mj.core.help()` for group-specific.',
                'Sandbox: No `setTimeout`, `setInterval`, `fetch`, or network access.',
                'Readonly: Pass `readonly: true` to `mj_execute_code` to restrict execution to read-only operations.',
                'Read `memory://help/codemode` for full namespace table, examples, and patterns.',
                '**Codemode-only**: When `mj_execute_code` is the only registered tool, all tool names referenced in these instructions (e.g., `create_entry`, `search_entries`) must be called via `mj_execute_code` using `mj.*` namespaces or bare globals. Do NOT call them as direct MCP tools.',
            ].join('\n')
        ) +
        BT
)
lines.push('')

lines.push('/**')
lines.push(' * All help keys that have content (for dynamic help pointer generation).')
lines.push(' */')
lines.push('const HELP_GROUP_KEYS: readonly string[] = ' + JSON.stringify(helpGroupKeys))
lines.push('')

lines.push('/**')
lines.push(' * Build dynamic help pointers listing only the enabled groups.')
lines.push(' */')
lines.push('function buildHelpPointers(groups: Set<ToolGroup>): string {')
lines.push('    const enabledHelpGroups = HELP_GROUP_KEYS.filter((k) => {')
lines.push("        if (k === 'hush-protocol') return groups.has('team')")
lines.push("        if (k === 'skills') return true")
lines.push('        return groups.has(k as ToolGroup)')
lines.push('    })')
lines.push('    if (enabledHelpGroups.length === 0) {')
lines.push("        return '\\n\\nRead `memory://help` for gotchas and critical usage patterns.'")
lines.push('    }')
lines.push("    return '\\n\\n## Available Help\\n\\n' +")
lines.push("        'Read `memory://help` for gotchas and critical usage patterns.\\n' +")
lines.push("        'Read `memory://help/{group}` for: ' + enabledHelpGroups.join(', ') + '.'")
lines.push('}')
lines.push('')

lines.push('/**')
lines.push(' * Build active groups summary listing enabled group names with tool counts.')
lines.push(' */')
lines.push('function buildActiveGroupsSummary(enabledTools: Set<string>): string {')
lines.push('    const activeGroups: { group: ToolGroup; tools: string[] }[] = []')
lines.push('')
lines.push(
    '    for (const [group, allTools] of Object.entries(TOOL_GROUPS) as [ToolGroup, string[]][]) {'
)
lines.push('        const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool))')
lines.push('        if (enabledInGroup.length > 0) {')
lines.push('            activeGroups.push({ group, tools: enabledInGroup })')
lines.push('        }')
lines.push('    }')
lines.push('')
lines.push("    if (activeGroups.length === 0) return ''")
lines.push('')
lines.push('    let summary = `\\n\\n## Active Tools (${String(enabledTools.size)})\\n`')
lines.push('    for (const { group, tools } of activeGroups) {')
lines.push("        summary += `**${group}**: ${tools.map((t) => `\\`${t}\\``).join(', ')}\\n`")
lines.push('    }')
lines.push('    return summary')
lines.push('}')
lines.push('')

// ==========================================================================
// Public API
// ==========================================================================

lines.push('// =============================================================================')
lines.push('// Public API')
lines.push('// =============================================================================')
lines.push('')
lines.push('/**')
lines.push(' * Generate dynamic instructions based on enabled tool groups and instruction level.')
lines.push(' *')
lines.push(' * Sections are conditionally included based on which tool groups are enabled:')
lines.push(' * - Code Mode snippet → only with `codemode` group')
lines.push(' * - Help group listing → `standard`+ level, only lists enabled groups')
lines.push(' * - Active tools summary → `full` level only')
lines.push(' * - Prompts listing → `full` level only')
lines.push(' *')
lines.push(' * @param enabledTools - Set of enabled tool names')
lines.push(' * @param prompts - Available prompt definitions')
lines.push(' * @param latestEntry - Optional latest entry for context snapshot')
lines.push(" * @param level - Instruction detail level (default: 'standard')")
lines.push(
    ' * @param enabledGroups - Optional pre-computed enabled groups; derived from enabledTools if omitted'
)
lines.push(' */')
lines.push('export function generateInstructions(')
lines.push('    enabledTools: Set<string>,')
lines.push('    prompts: PromptDefinition[],')
lines.push('    latestEntry?: LatestEntrySnapshot,')
lines.push("    level: InstructionLevel = 'standard',")
lines.push('    enabledGroups?: Set<ToolGroup>')
lines.push('): string {')
lines.push('    // Derive enabled groups from enabled tools if not provided (backward compat)')
lines.push('    const groups = enabledGroups ?? getEnabledGroups(enabledTools)')
lines.push('')
lines.push('    // Always start with core instructions (overview + behaviors)')
lines.push('    let instructions = CORE_INSTRUCTIONS')
lines.push('')
lines.push('    // Code Mode snippet — only when codemode group is enabled')
lines.push("    if (groups.has('codemode')) {")
lines.push('        instructions += CODE_MODE_INSTRUCTIONS')
lines.push('    }')
lines.push('')
lines.push('    // Add latest entry snapshot for immediate context (compact format)')
lines.push('    if (latestEntry) {')
lines.push('        const preview = latestEntry.content.slice(0, 120)')
lines.push(
    "        instructions += `\\n**Latest**: #${String(latestEntry.id)} (${latestEntry.timestamp}) ${latestEntry.entryType}\\n> ${preview}${latestEntry.content.length > 120 ? '...' : ''}\\n`"
)
lines.push('    }')
lines.push('')
lines.push('    // Essential: minimal help pointer (no group listing)')
lines.push('    // Standard+: dynamic help pointers listing enabled groups')
lines.push("    if (level === 'essential') {")
lines.push(
    "        instructions += '\\n\\nRead `memory://help` for gotchas and critical usage patterns.'"
)
lines.push('    } else {')
lines.push('        instructions += buildHelpPointers(groups)')
lines.push('    }')
lines.push('')
lines.push('    // Full level includes active groups summary + prompts')
lines.push("    if (level === 'full') {")
lines.push('        instructions += buildActiveGroupsSummary(enabledTools)')
lines.push('')
lines.push('        // Add prompts section')
lines.push('        if (prompts.length > 0) {')
lines.push('            instructions += `\\n## Prompts (${String(prompts.length)})\\n`')
lines.push("            instructions += 'Pre-built templates and guided workflows:\\n'")
lines.push('            for (const prompt of prompts) {')
lines.push(
    "                instructions += `- \\`${prompt.name}\\` - ${prompt.description ?? ''}\\n`"
)
lines.push('            }')
lines.push('        }')
lines.push('    }')
lines.push('')
lines.push('    return instructions')
lines.push('}')
lines.push('')

// Static backward compat
lines.push('/**')
lines.push(' * Static instructions for backward compatibility.')
lines.push(' * @deprecated Use generateInstructions() instead for dynamic content')
lines.push(' */')
lines.push('export const SERVER_INSTRUCTIONS = CORE_INSTRUCTIONS')
lines.push('')

// ==========================================================================
// HELP_CONTENT map
// ==========================================================================

lines.push('/**')
lines.push(' * Help content keyed by group name.')
lines.push(" * 'gotchas' is the always-available help (memory://help).")
lines.push(' * Other keys are feature-specific help (memory://help/{key}).')
lines.push(' */')
lines.push('export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([')
for (const { key, content } of helpEntries) {
    const escaped = escapeForTemplateLiteral(content)
    lines.push('  [' + JSON.stringify(key) + ', ' + BT + escaped + BT + '],')
}
lines.push('])')
lines.push('')

const tsContent = lines.join('\n')
const tsPath = resolve(constantsDir, 'server-instructions.ts')
writeFileSync(tsPath, tsContent, 'utf-8')

process.stderr.write(
    [
        '',
        '✅ Generated server-instructions.ts (' +
            tsContent.length.toLocaleString() +
            ' bytes) from ' +
            (helpEntries.length + 1) +
            ' markdown files',
        '   Overview: ' + overviewMd.length.toLocaleString() + ' chars',
        '   Help entries: ' + helpEntries.map((e) => e.key).join(', '),
        '   Help group keys: ' + helpGroupKeys.join(', '),
        '   Exports: generateInstructions(), SERVER_INSTRUCTIONS (deprecated), HELP_CONTENT',
        '',
    ].join('\n')
)
