/**
 * Generates src/constants/server-instructions.ts from src/constants/server-instructions.md
 *
 * Reads the markdown source file, splits it by section delimiters,
 * escapes for template literals, and produces the full TypeScript module
 * with types, constants, and the generateInstructions function.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')

const mdPath = resolve(projectRoot, 'src/constants/server-instructions.md')
const tsPath = resolve(projectRoot, 'src/constants/server-instructions.ts')

// Read plain markdown source
const markdown = readFileSync(mdPath, 'utf-8')

// Section names in order
const SECTION_NAMES = ['ESSENTIAL', 'GITHUB', 'SERVER_ACCESS', 'TOOL_PARAMETER_REFERENCE']

/**
 * Parse sections from markdown using <!-- SECTION:NAME --> delimiters
 */
function parseSections(content) {
    const sections = {}

    for (let i = 0; i < SECTION_NAMES.length; i++) {
        const name = SECTION_NAMES[i]
        const startMarker = '<!-- SECTION:' + name + ' -->'
        const startIdx = content.indexOf(startMarker)

        if (startIdx === -1) {
            throw new Error('Missing section marker: ' + startMarker)
        }

        const contentStart = startIdx + startMarker.length

        // Find next section marker or end of file
        let contentEnd
        if (i + 1 < SECTION_NAMES.length) {
            const nextMarker = '<!-- SECTION:' + SECTION_NAMES[i + 1] + ' -->'
            contentEnd = content.indexOf(nextMarker)
            if (contentEnd === -1) {
                throw new Error('Missing section marker: ' + nextMarker)
            }
        } else {
            contentEnd = content.length
        }

        // Trim leading/trailing whitespace but preserve internal structure
        sections[name] = content.slice(contentStart, contentEnd).trim()
    }

    return sections
}

/**
 * Escape content for use inside a JS/TS template literal
 */
function escapeForTemplateLiteral(content) {
    return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

const sections = parseSections(markdown)

// Read the function body template (static TypeScript code after the constants)
const FUNCTION_BODY = readFileSync(
    resolve(projectRoot, 'scripts/server-instructions-function-body.ts'),
    'utf-8'
)

// Build the TypeScript file using string concatenation to avoid nested escaping
const lines = []

lines.push('/**')
lines.push(' * Server instructions for Memory Journal MCP.')
lines.push(' *')
lines.push(' * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY')
lines.push(' *     Edit src/constants/server-instructions.md instead,')
lines.push(' *     then run: npm run generate:instructions')
lines.push(' *')
lines.push(' * These instructions are automatically sent to MCP clients during initialization,')
lines.push(' * providing guidance for AI agents on tool usage.')
lines.push(' *')
lines.push(' * Optimized for token efficiency with tiered instruction levels.')
lines.push(' */')
lines.push('')
lines.push("import type { ToolGroup } from '../types/index.js'")
lines.push("import { TOOL_GROUPS } from '../filtering/tool-filter.js'")
lines.push('')
lines.push('/**')
lines.push(' * Resource definition for instruction generation')
lines.push(' */')
lines.push('export interface ResourceDefinition {')
lines.push('    uri: string')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Prompt definition for instruction generation')
lines.push(' */')
lines.push('export interface PromptDefinition {')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Latest entry snapshot for initial briefing')
lines.push(' */')
lines.push('export interface LatestEntrySnapshot {')
lines.push('    id: number')
lines.push('    timestamp: string')
lines.push('    entryType: string')
lines.push('    content: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Instruction detail level for token efficiency')
lines.push(' * - essential: ~200 tokens - Core behaviors only (for token-constrained clients)')
lines.push(' * - standard: ~400 tokens - + GitHub patterns (default)')
lines.push(' * - full: ~600 tokens - + tool/resource listings')
lines.push(' */')
lines.push("export type InstructionLevel = 'essential' | 'standard' | 'full'")
lines.push('')
lines.push('/**')
lines.push(' * Essential behavioral guidance (~200 tokens)')
lines.push(' * Core patterns every AI agent should follow.')
lines.push(' */')
lines.push(
    'const ESSENTIAL_INSTRUCTIONS = `' + escapeForTemplateLiteral(sections.ESSENTIAL) + '\n`'
)
lines.push('')
lines.push('/**')
lines.push(' * GitHub integration patterns (~150 additional tokens)')
lines.push(' */')
lines.push('const GITHUB_INSTRUCTIONS = `\n' + escapeForTemplateLiteral(sections.GITHUB) + '\n`')
lines.push('')
lines.push('/**')
lines.push(' * Server access instructions - critical for AI agents to call tools correctly')
lines.push(' */')
lines.push(
    'const SERVER_ACCESS_INSTRUCTIONS = `\n' +
        escapeForTemplateLiteral(sections.SERVER_ACCESS) +
        '\n`'
)
lines.push('')
lines.push('/**')
lines.push(' * Tool parameter reference - essential for correct tool invocation')
lines.push(' */')
lines.push(
    'const TOOL_PARAMETER_REFERENCE = `\n' +
        escapeForTemplateLiteral(sections.TOOL_PARAMETER_REFERENCE) +
        '\n`'
)
lines.push('')
lines.push(FUNCTION_BODY)
lines.push('')

const tsContent = lines.join('\n')

writeFileSync(tsPath, tsContent, 'utf-8')

process.stderr.write(
    '✅ Generated server-instructions.ts (' +
        tsContent.length.toLocaleString() +
        ' bytes) from server-instructions.md (' +
        markdown.length.toLocaleString() +
        ' bytes)\n'
)
