/**
 * Generates src/constants/server-instructions.ts from src/constants/server-instructions.md
 *
 * Reads the markdown source file, splits it by section delimiters,
 * escapes for template literals, and produces the full TypeScript module
 * with types, constants, and the generateInstructions function.
 *
 * Sections: CORE, COPILOT, CODE_MODE, GITHUB, HELP_POINTERS, SERVER_ACCESS
 * CORE is always included. COPILOT and CODE_MODE are conditionally included
 * based on enabled tool groups. GITHUB is conditional at standard+ level.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')

const mdPath = resolve(projectRoot, 'src/constants/server-instructions.md')
const tsPath = resolve(projectRoot, 'src/constants/server-instructions.ts')

// Read plain markdown source
const markdown = readFileSync(mdPath, 'utf-8')

// Section names in order
const SECTION_NAMES = ['CORE', 'COPILOT', 'CODE_MODE', 'GITHUB', 'HELP_POINTERS', 'SERVER_ACCESS']

/**
 * Parse sections from markdown using <!-- SECTION:NAME --> delimiters
 */
function parseSections(content: string): Record<string, string> {
    const sections: Record<string, string> = {}

    for (let i = 0; i < SECTION_NAMES.length; i++) {
        const name = SECTION_NAMES[i]
        const startMarker = '<!-- SECTION:' + name + ' -->'
        const startIdx = content.indexOf(startMarker)

        if (startIdx === -1) {
            throw new Error('Missing section marker: ' + startMarker)
        }

        const contentStart = startIdx + startMarker.length

        // Find next section marker or end of file
        let contentEnd
        if (i + 1 < SECTION_NAMES.length) {
            const nextMarker = '<!-- SECTION:' + SECTION_NAMES[i + 1] + ' -->'
            contentEnd = content.indexOf(nextMarker)
            if (contentEnd === -1) {
                throw new Error('Missing section marker: ' + nextMarker)
            }
        } else {
            contentEnd = content.length
        }

        // Trim leading/trailing whitespace but preserve internal structure
        sections[name] = content.slice(contentStart, contentEnd).trim()
    }

    return sections
}

/**
 * Escape content for use inside a JS/TS template literal
 */
function escapeForTemplateLiteral(content: string): string {
    return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

const sections = parseSections(markdown)

// Read the function body template (static TypeScript code after the constants)
const FUNCTION_BODY = readFileSync(
    resolve(projectRoot, 'scripts/server-instructions-function-body.ts'),
    'utf-8'
)

// Read the gotchas content (kept as a separate const, not in .md sections)
const GOTCHAS_BODY = readFileSync(
    resolve(projectRoot, 'scripts/server-instructions-gotchas.ts'),
    'utf-8'
)

// Build the TypeScript file using string concatenation to avoid nested escaping
const lines = []

lines.push('/**')
lines.push(' * Server instructions for Memory Journal MCP.')
lines.push(' *')
lines.push(' * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY')
lines.push(' *     Edit src/constants/server-instructions.md instead,')
lines.push(' *     then run: npm run generate:instructions')
lines.push(' *')
lines.push(' * These instructions are automatically sent to MCP clients during initialization,')
lines.push(' * providing guidance for AI agents on tool usage.')
lines.push(' *')
lines.push(' * Tool parameter reference is served dynamically via memory://help/{group}.')
lines.push(' * Field notes and gotchas are served via memory://help/gotchas.')
lines.push(' *')
lines.push(' * Optimized for token efficiency with tiered instruction levels.')
lines.push(' * Sections are conditionally included based on enabled tool groups.')
lines.push(' */')
lines.push('')
lines.push("import type { ToolGroup } from '../types/index.js'")
lines.push("import { TOOL_GROUPS, getEnabledGroups } from '../filtering/tool-filter.js'")
lines.push('')
lines.push('/**')
lines.push(' * Resource definition for instruction generation')
lines.push(' */')
lines.push('export interface ResourceDefinition {')
lines.push('    uri: string')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Prompt definition for instruction generation')
lines.push(' */')
lines.push('export interface PromptDefinition {')
lines.push('    name: string')
lines.push('    description?: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Latest entry snapshot for initial briefing')
lines.push(' */')
lines.push('export interface LatestEntrySnapshot {')
lines.push('    id: number')
lines.push('    timestamp: string')
lines.push('    entryType: string')
lines.push('    content: string')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Instruction detail level for token efficiency')
lines.push(' * - essential: ~200 tokens - Core behaviors only (for token-constrained clients)')
lines.push(' * - standard: ~350 tokens - + GitHub patterns + help pointers')
lines.push(' * - full: ~400 tokens - + active tools/prompts summary')
lines.push(' */')
lines.push("export type InstructionLevel = 'essential' | 'standard' | 'full'")
lines.push('')

// ---- Composable Segments ----

lines.push('// =============================================================================')
lines.push('// Composable Instruction Segments')
lines.push('// =============================================================================')
lines.push('')
lines.push('/**')
lines.push(' * Core behavioral guidance — always included regardless of enabled groups.')
lines.push(' * Session Start, Behaviors, Rule & Skill Suggestions.')
lines.push(' */')
lines.push('const CORE_INSTRUCTIONS = `' + escapeForTemplateLiteral(sections.CORE) + '\n`')
lines.push('')
lines.push('/**')
lines.push(' * Copilot Review Patterns — only when `github` group is enabled.')
lines.push(' * References `get_copilot_reviews` which is a GitHub tool.')
lines.push(' */')
lines.push(
    'const COPILOT_REVIEW_INSTRUCTIONS = `\\n' + escapeForTemplateLiteral(sections.COPILOT) + '\n`'
)
lines.push('')
lines.push('/**')
lines.push(' * Quick Access table — always included.')
lines.push(' * The semantic_search row is conditional on the `search` group.')
lines.push(' */')
lines.push('function buildQuickAccess(groups: Set<ToolGroup>): string {')
lines.push('    let table = `')
lines.push('## Quick Access')
lines.push('')
lines.push('| Purpose         | Action                      |')
lines.push('| --------------- | --------------------------- |')
lines.push('| Session context | \\`memory://briefing\\`         |')
lines.push('| Recent entries  | \\`memory://recent\\`           |')
lines.push('| Health/time     | \\`memory://health\\`           |')
lines.push('`')
lines.push("    if (groups.has('search')) {")
lines.push('        table += `| Semantic search | \\`semantic_search(query)\\`    |')
lines.push('`')
lines.push('    }')
lines.push('    table += `| Full context    | \\`get-context-bundle\\` prompt |')
lines.push('`')
lines.push('    return table')
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Code Mode namespace row definitions.')
lines.push(' * Each maps a tool group to its Code Mode API namespace.')
lines.push(' */')
lines.push(
    'const CODE_MODE_NAMESPACE_ROWS: { group: ToolGroup; label: string; namespace: string; example: string }[] = ['
)
lines.push(
    "    { group: 'core', label: 'Core', namespace: '`mj.core.*`', example: '`mj.core.createEntry(\"Implemented feature X\")`' },"
)
lines.push(
    "    { group: 'search', label: 'Search', namespace: '`mj.search.*`', example: '`mj.search.searchEntries(\"performance\")`' },"
)
lines.push(
    "    { group: 'analytics', label: 'Analytics', namespace: '`mj.analytics.*`', example: '`mj.analytics.getStatistics()`' },"
)
lines.push(
    "    { group: 'relationships', label: 'Relationships', namespace: '`mj.relationships.*`', example: '`mj.relationships.linkEntries(1, 2, \"implements\")`' },"
)
lines.push(
    "    { group: 'io', label: 'IO', namespace: '`mj.io.*`', example: '`mj.io.importMarkdown(\"content\")`' },"
)
lines.push(
    "    { group: 'io', label: 'Export', namespace: '`mj.export.*`', example: '`mj.export.exportEntries(\"json\")`' },"
)
lines.push(
    "    { group: 'admin', label: 'Admin', namespace: '`mj.admin.*`', example: '`mj.admin.rebuildVectorIndex()`' },"
)
lines.push(
    "    { group: 'github', label: 'GitHub', namespace: '`mj.github.*`', example: '`mj.github.getGithubIssues({ state: \"open\" })`' },"
)
lines.push(
    "    { group: 'backup', label: 'Backup', namespace: '`mj.backup.*`', example: '`mj.backup.backupJournal()`' },"
)
lines.push(
    "    { group: 'team', label: 'Team', namespace: '`mj.team.*`', example: '`mj.team.teamCreateEntry(\"Team update\")`' },"
)
lines.push(']')
lines.push('')
lines.push('/**')
lines.push(' * Code Mode section — only when `codemode` group is enabled.')
lines.push(' * The namespace table dynamically omits rows for disabled groups.')
lines.push(
    ' * The behavioral text (await patterns, readonly, return shape) comes from the .md source.'
)
lines.push(' */')
lines.push('function buildCodeModeInstructions(groups: Set<ToolGroup>): string {')
lines.push('    // Build namespace table with only enabled groups')
lines.push('    const rows = CODE_MODE_NAMESPACE_ROWS')
lines.push('        .filter((r) => groups.has(r.group))')
lines.push(
    '        .map((r) => `| ${r.label.padEnd(13)} | ${r.namespace.padEnd(20)} | ${r.example.padEnd(50)} |`)'
)
lines.push("        .join('\\n')")
lines.push('')
lines.push('    // Build the static behavioral text from the .md source,')
lines.push('    // but replace the full namespace table with the filtered version')
lines.push('    const fullSection = CODE_MODE_FULL_TEXT')
lines.push("    const tableStart = fullSection.indexOf('| Group')")
lines.push("    const tableEnd = fullSection.indexOf('\\n\\n**Features**')")
lines.push('    if (tableStart === -1 || tableEnd === -1) {')
lines.push('        // Fallback: return full section if markers not found')
lines.push("        return '\\n' + fullSection")
lines.push('    }')
lines.push('    const beforeTable = fullSection.slice(0, tableStart)')
lines.push(
    "    const headerLine = '| Group         | Namespace            | Example                                            |'"
)
lines.push(
    "    const separatorLine = '| ------------- | -------------------- | -------------------------------------------------- |'"
)
lines.push('    const afterTable = fullSection.slice(tableEnd)')
lines.push(
    "    return '\\n' + beforeTable + headerLine + '\\n' + separatorLine + '\\n' + rows + afterTable"
)
lines.push('}')
lines.push('')
lines.push('/**')
lines.push(' * Full Code Mode section text from .md source (used as template for filtered version)')
lines.push(' */')
lines.push('const CODE_MODE_FULL_TEXT = `' + escapeForTemplateLiteral(sections.CODE_MODE) + '\n`')
lines.push('')

// ---- Original static sections ----
lines.push('/**')
lines.push(' * GitHub integration patterns (~150 additional tokens)')
lines.push(' * Only included when `github` group is enabled.')
lines.push(' */')
lines.push('const GITHUB_INSTRUCTIONS = `\\n' + escapeForTemplateLiteral(sections.GITHUB) + '\n`')
lines.push('')
lines.push('/**')
lines.push(' * Help resource pointers — directs agents to pull-based reference')
lines.push(' */')
lines.push('const HELP_POINTERS = `\\n' + escapeForTemplateLiteral(sections.HELP_POINTERS) + '\n`')
lines.push('')
lines.push('/**')
lines.push(' * Server access instructions - critical for AI agents to call tools correctly')
lines.push(' */')
lines.push(
    'const SERVER_ACCESS_INSTRUCTIONS = `\\n' +
        escapeForTemplateLiteral(sections.SERVER_ACCESS) +
        '\n`'
)
lines.push('')
lines.push(GOTCHAS_BODY)
lines.push('')
lines.push(FUNCTION_BODY)
lines.push('')

const tsContent = lines.join('\n')

writeFileSync(tsPath, tsContent, 'utf-8')

process.stderr.write(
    '✅ Generated server-instructions.ts (' +
        tsContent.length.toLocaleString() +
        ' bytes) from server-instructions.md (' +
        markdown.length.toLocaleString() +
        ' bytes)\n'
)
