name: Secret Scanning

on:
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scanning
        uses: trufflesecurity/trufflehog@6c64db94d5b2e09d7e0948fb6bd3166cc6fffbc7 # v3.94.0
        with:
          path: ./
          base: ${{ github.event.before || 'HEAD~1' }}
          head: HEAD
          extra_args: --only-verified

      - name: GITLEAKS Secret Scanning
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
